title: Glossário 
description: Este é um repositório de termos e conceitos da Igreja Católica no Brasil orientado ao CDIC-BR.
theme: just-the-docs
url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
