# -----------------------------------
# Configurações do site
# -----------------------------------
title: Glossário CDIC-BR
description: Seu site em Jekyll com o tema Just the Docs.
theme: just-the-docs
url: https://just-the-docs.github.io

# -----------------------------------
# Configurações do logo
# -----------------------------------
logo: "/assets/CNBB.png"

# -----------------------------------
# Parser de Markdown
# -----------------------------------
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  parse_block_html: true # Permite HTML dentro do Markdown
  syntax_highlighter_opts:
    disable: true
highlighter: rouge

# -----------------------------------
# Configurações de Front Matter Padrão (Defaults)
# -----------------------------------
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page" # Corrigido para 'page'

# -----------------------------------
# Configurações de Navegação (Sidebar)
# -----------------------------------
nav_pages:
  - title: "Home"
    url: "/home.html"
  - title: "Glossário"
    url: "/glossario.html"
    - title: "Área Pessoal"
    url: "/1-area-pessoal.html"
  - title: "CNBB"
    url: "/3-cnbb.html"
  - title: "Fiéis"
    url: "/4-fieis.html"
    - title: "Igreja Particular"
    url: "/5-igreja.html"
  - title: "Formação Clerical e Laical"
    url: "/6-formacao.html"
  - title: "IVC e SVA"
    url: "/7-ivc_sva.html"
  - title: "Cadastros"
    url: "/8-cadastros.html"
    subpages:
      - title: "Configuração"
        url: "/9-configuracao.html"
      - title: "Dashboard"
        url: "/2-dashboard.html"

# -----------------------------------
# Configurações da Barra de Pesquisa
# -----------------------------------
search_enabled: true
search_placeholder: "Pesquisar Glossário CDIC-BR"

# -----------------------------------
# Opções Extras
# -----------------------------------
heading_anchors: true
compress_html:
  clippings: all
  comments: false # Corrigido para 'false'
  endings: all
  startings: [head, body]
